language: node_js
node_js:
  - node
env:
  - MONGODB_URI=mongodb+srv://user1:pass1@mmlearnjs-cluster0-egfri.mongodb.net/data?retryWrites=true&w=majority'
  - JWT_SECRET=myrandomsecretsecretjwtkeythatnoonewilleverfindoutaboutihope